# 1: Build de la app con Node 18
FROM node:20.14.0 AS build

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de configuración y dependencias
COPY package*.json ./

# Instalar dependencias forzando resolución limpia para evitar conflictos como el de esbuild
RUN npm install --force

# Copiar el resto del código de la aplicación
COPY . .

# Compilar la aplicación React con Vite
RUN npm run build

# 2: Etapa final - Servir el build con NGINX
FROM nginx:alpine

# Copiar archivos compilados desde el contenedor de build al directorio público de nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración personalizada para manejar rutas SPA y proxy a backend
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 (el estándar en NGINX)
EXPOSE 80

# Comando de inicio del servidor NGINX
CMD ["nginx", "-g", "daemon off;"]