# 1: Build de la app con Node 20
FROM node:20.14.0 AS build

WORKDIR /app

# Copiar dependencias y preparar entorno
COPY package*.json ./
RUN npm install --force
COPY . .

# Recibir la variable del backend
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Reemplazar la constante API_URL en el archivo env.js
RUN sed -i "s|export const API_URL = .*|export const API_URL = '$VITE_API_URL';|" src/config/env.js

# Compilar React con Vite
RUN npm run build

# 2: Imagen final con NGINX
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
