# Imagen base
FROM node:20.14.0

# Directorio de trabajo
WORKDIR /app

# Copiar e instalar dependencias
COPY package*.json ./

#  instalar con reconstrucción de binarios nativos
RUN npm install

# Copiar el resto del código 
COPY . .

# Exponer el puerto
EXPOSE 8080

# Comando para iniciar la API
CMD ["npx", "nodemon", "index.js"]