export const OBSERVATION_CODES = [
  { code: "00", label: "literal_observation_00" },
  { code: "01", label: "literal_observation_01" },
  { code: "02", label: "literal_observation_02" },
  { code: "03", label: "literal_observation_03" },
  { code: "04", label: "literal_observation_04" },
  { code: "05", label: "literal_observation_05" },
  { code: "06", label: "literal_observation_06" },
  { code: "07", label: "literal_observation_07" },
  { code: "08", label: "literal_observation_08" },
  { code: "09", label: "literal_observation_09" },
  { code: "10", label: "literal_observation_10" },
  { code: "11", label: "literal_observation_11" },
  { code: "12", label: "literal_observation_12" },
  { code: "13", label: "literal_observation_13" },
  { code: "14", label: "literal_observation_14" },
  { code: "15", label: "literal_observation_15" },
  { code: "16", label: "literal_observation_16" },
  { code: "17", label: "literal_observation_17" },
  { code: "18", label: "literal_observation_18" },
  { code: "19", label: "literal_observation_19" },
  { code: "20", label: "literal_observation_20" },
  { code: "21", label: "literal_observation_21" },
  { code: "22", label: "literal_observation_22" },
  { code: "23", label: "literal_observation_23" },
];
