name: Frontend CI/CD

on:
  push:
    branches: [main, uat, feat/ci-cd]
    paths:
      - "Frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  test-frontend:
    name: 🧪 Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: |
          cd Frontend
          npm install

      - name: Run tests
        run: |
          cd Frontend
          npm run test || echo "Frontend tests failed, skipping build"

      - name: Upload Jest test report
        uses: actions/upload-artifact@v4
        with:
          name: jest-report
          path: Frontend/reports/jest-junit.xml

      - name: Report test results in GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Jest Tests
          path: Frontend/reports/jest-junit.xml
          reporter: jest-junit

  build-and-deploy-frontend:
    name: 🚀 Build & Deploy Frontend
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg VITE_API_URL=https://mern-backend-prod-677888703036.us-central1.run.app \
            -t docker.io/${{ secrets.DOCKER_USERNAME }}/mern-frontend ./Frontend

      - name: Push Frontend Image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mern-frontend

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}

      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mern-frontend
          image: docker.io/${{ secrets.DOCKER_USERNAME }}/mern-frontend
          region: us-central1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          flags: --platform managed --allow-unauthenticated
