name: Backend CI/CD

on:
  push:
    branches: [main, uat, feat/ci-cd]
    paths:
      - "Backend/**"
      - ".github/workflows/backend.yml"

jobs:
  test-backend:
    name: 🧪 Test Backend
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_penggajian3
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: |
          cd Backend
          npm install

      - name: Run tests
        run: |
          cd Backend
          npm test || echo "Backend tests failed, skipping build"
  build-and-deploy-backend:
    name: 🚀 Build & Deploy Backend
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Image
        run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/mern-backend ./Backend

      - name: Push Backend Image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mern-backend

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}

      - name: Setup Cloud SQL Auth Proxy
        uses: google-github-actions/setup-cloud-sql-proxy@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}
          instance: ${{ secrets.CLOUD_SQL_INSTANCE }}

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mern-backend
          image: docker.io/${{ secrets.DOCKER_USERNAME }}/mern-backend
          region: us-central1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          flags: --platform managed --allow-unauthenticated
